version: "3"
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      APP_DB_USER: ${WMS_DB_USER}
      APP_DB_PASS: ${WMS_DB_PASS}
      APP_DB_NAME: ${WMS_DB_NAME}
    ports:
      - "${WMS_DB_PORT}:5432"
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d/